### ISSUE TITLE
No Hidden Entries when next entry is Empty

### ISSUE THREAD

**Issue by xesf** [LBALab/hqr#2]
Thanks Seb for reporting this issue.

## Current Behavior

Hidden Entries are not been parsed when next entry is empty.
Entry 61 from EN_GAM.VOX should have hidden entries.

<img width="742" alt="image" src="https://user-images.githubusercontent.com/751076/235354338-ed0eedd8-2bb2-4c45-9ae6-b78b0d07e131.png">

## Steps to Reproduce the Problem

  1. Open EN_GAM.VOX or any orther XX_GAM.VOX HQR file
  2. Locate entry 61
  3. Entry 61 should have 3 hidden entries.

**Comment by sviannay** [comment]
Maybe I could add it as a contrib Pull Request, but one working workaround is to replace in HQRReader.ts, function read(), the line 67 which look at next entry offset:
```
const nextOffset = this.entriesIndex[i + 1];
```
with a loop to get next entries index while it's an empty entry and we not reached end of HQR buffer (in this cas we would take buffer length).

Here's is a diff for a proposal fix implementation (maybe it would even be more elegant to move it in a dedicated getNextOffset(i) or similar function):

```
diff --git a/src/HQRReader.ts b/src/HQRReader.ts
index bbb08e3..07e9675 100644
--- a/src/HQRReader.ts
+++ b/src/HQRReader.ts
@@ -64,7 +64,18 @@ export default class HQRReader {
       }

       /* Read associated hidden entries */
-      const nextOffset = this.entriesIndex[i + 1];
+      let nextOffset = 0;
+
+      /* search for next non empty entry */
+      for (let j = i+1; !nextOffset && (j < this.numEntries); j += 1) {
+        nextOffset = this.entriesIndex[j];
+      }
+
+      if(!nextOffset) {
+        /* when entry is the latest non empty, use HQR size as nextOffset */
+        nextOffset = this.buffer.byteLength;
+      }
+
       let computedOffset = this.computeNextOffset(entryInfo);
       while (computedOffset < nextOffset) {
         const hiddenEntryInfo = this.readEntryInfo(computedOffset);
```
Notes:
- I only tested on LBA1 xx_GAM.VOX file to check entry 61, and not check if this should be backported or used in any other piece of code, reason I did not make a full PR.
- To test, I used the provided `test\count-hidden.ts` script which now outputs at the end:
```
Entry 61 has 3 hidden entries:
  Hidden entry #0: 167304 bytes
  Hidden entry #1: 196134 bytes
  Hidden entry #2: 134373 bytes
```
instead of:
```
Entry 61 has 0 hidden entries:
```
Wich match correct entries from original.

**Comment by xesf** [comment]
Thanks @sviannay, I can confirm it works fine.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/751076/235515089-2515c397-cf22-4e1d-8a74-afc36efe37b1.png">

I was missing the last part "nextOffset = this.buffer.byteLength;" when I tried the other day and getting some weird issues.

I will patch it, release a new version, update the packager editor and the lba denoise.
I will let you know when that's done.

**Comment by agrande** [comment]
I'm late to the party, but the changes look good to me!
Thanks @sviannay for the patch, I didn't know about that particular usecase, and thanks @xesf for applying the changes and publishing a new version.
